### ISSUE TITLE
:sparkles: **As a customer/visitor, I want to be able to:** :sparkles:

### ISSUE THREAD

**Issue by AshleeKP** [2006-GHP-GS-TEAMSUICUNE/GRACE-SHOPPER#21]
- [ ] access a deployed version of the website so I can browse and purchase products. #6 
- [x] view all available products so I can pick from a variety. #7 
- [x] view a single product so I can see more details. #4 
- [ ] add a product to my cart so I can collect my desired products in one place. #8 
- [ ] edit my cart if I change my mind:
  - [ ] change the quantity of a product in my cart. #20 
  - [ ] remove a product in my cart. #19 
  - [ ] No one else should be able to edit my cart except me. #18 
- [ ] "checkout" the items in my cart so I can purchase my desired goods. #17 
  - [ ]Think of a typical user experience on popular websites from a guest user and logged-in user perspective. #16 ( as guest ) #17  (as user)
  - [ ] You can just start with by simulating the experience of checking out with a simple confirmation page. #26
- [ ] create an account so I can have a logged-in experience. #15
