### ISSUE TITLE
:sparkles:**As an administrator, I want to be able to:**:sparkles:

### ISSUE THREAD

**Issue by AshleeKP** [2006-GHP-GS-TEAMSUICUNE/GRACE-SHOPPER#22]
- [ ] have validated data to ensure reliability.
    - [ ] *i.e. each customer that creates an account should only be able to do so once with a single email address.* #24 
- [ ] have full rights to make backend requests to add, edit, and remove products. #25
    - [ ] *No one else should have access.*
- [ ] view user information. #25
    - [ ] *No one else should have access.*
