### ISSUE TITLE
**:sparkles: As a logged-in customer, I want to be able to: ✨**

### ISSUE THREAD

**Issue by AshleeKP** [2006-GHP-GS-TEAMSUICUNE/GRACE-SHOPPER#9]
- [ ] have a persistent cart so I can revisit and pick up where I left off. #14 
   - [ ] Logged-in-user across multiple devices: I'm logged in on my mobile device and add some items to my cart. When I open the browser on my laptop and log in, I want to see those items in my cart. #13 
   - [ ] No one else should be able to edit my cart except me. #12
